name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  ios-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
      env:
        FLUTTER_ROOT: /usr/local
        FLUTTER_VERSION: 3.16.5
        
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace NumberOCR.xcworkspace -scheme NumberOCR -configuration Release -destination 'generic/platform=iOS' -archivePath NumberOCR.xcarchive archive
      env:
        FLUTTER_ROOT: /usr/local
        FLUTTER_VERSION: 3.16.5
        
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ios/NumberOCR.xcarchive 